name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      # Set up SonarQube Scanner
      - name: Set up SonarQube Scanner
        run: |
          # Set the path to the SonarQube Scanner installation folder
          $env:SONAR_SCANNER_HOME = "C:\Users\Abdul\Downloads\sonar-scanner-cli-6.2.1.4610-windows-x64\sonar-scanner"
          # Add the scanner binary directory to PATH
          $env:Path += ";$env:SONAR_SCANNER_HOME\bin"
          
          # Log the current PATH to ensure it's been updated
          Write-Host "Current PATH: $env:Path"
          
          # Verify that sonar-scanner is now in the PATH and accessible
          if (Test-Path "$env:SONAR_SCANNER_HOME\bin\sonar-scanner.bat") {
            Write-Host "sonar-scanner.bat found!"
          } else {
            Write-Host "sonar-scanner.bat NOT found!"
          }
          # Run sonar-scanner to verify if the tool is working
          sonar-scanner.bat --version
        shell: pwsh

      # Run the SonarQube scan
      - name: SonarQube Scan
        env:
          SONAR_SCANNER_HOME: "C:\Users\Abdul\Downloads\sonar-scanner-cli-6.2.1.4610-windows-x64\sonar-scanner"
          PATH: ${{ env.PATH }};${{ env.SONAR_SCANNER_HOME }}\bin
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://5268-114-79-138-251.ngrok-free.app
        run: |
          sonar-scanner.bat
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          scannerVersion: 6.2.1.4610
          scannerBinariesUrl: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli
